CC     = gcc
CFLAGS = -Wall -Wextra -O2 -g

TARGET  = RayTracer-Project
SRCS    = Worker.c RayTracer.c PPM.c main.c 
OBJS    = $(SRCS:.c=.o)
HEADERS = CommunicationsProtocol.h RayTracer.h PPM.h Worker.h ImageStructs.h

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) -o $@ $^ -lm

%.o: %.c $(HEADERS)
	$(CC) $(CFLAGS) -c -o $@ $<

run: $(TARGET)
	./$(TARGET) -w 600 -h 800 -j 32 -s 32 -t 8 -o Output.ppm

clean:
	rm -f $(OBJS) $(TARGET) *.ppm

.PHONY: all run clean