CC = gcc

CFLAGS = -Wall -Wextra -O2 -g

TARGET = Raytracer-Project
SRCS = main.c Worker.c RayTracer.c PPM.c 
OBJS = ($SRCS:.c=.o)
HEADERS = CommunicationsProtocol.h RayTracer.h PPM.h Worker.h ImageStructs.h

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) -o $@ $^ 

%.o: %.c $HEADERS
	$(CC) $(CFLAGS) -c -o $@ $<

run: $(TARGET)
	./$(TARGET) -w 400 -h 300 -j 4-s 2 -o Output.ppm


clean:
	rm -f $(OBJS) $(TARGET) output.ppm

.PHONY: all run view clean

